### ISSUE TITLE
segfault in LuescherZeta

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#42]
I want to generate a plot of the `w_lm` versus `q`. For this I have first calculated `w_00` in the P² = 0 frame, that worked fine. Now with various P², various l and m I face R crashes coming from the LuescherZeta function.

![screenshot_20180622_214746](https://user-images.githubusercontent.com/976924/41797328-e42b301e-7669-11e8-817a-e179c3904293.png)

Before you say that it is RStudio to blame, I have also tried this in a regular plain `Rscript`. Output (using `pbmclapply`) is this:

```
 *** caught segfault ***
address 0x5630fc94f000, cause 'memory not mapped'

Traceback:
 1: LuescherZeta(qsq = rel_momentum_q^2, l = spin_l, m = spin_m,     dvec = total_momentum_d_vec, gamma = boost_gamma, ...)
 2: scattering_w_lm(q, total_momentum_d_vec, grid$gamma[i], 1, grid$l[i],     grid$m[i])
 3: data.frame(spin_l = grid$l[i], spin_m = grid$m[i], boost_gamma = grid$gamma[i],     w = scattering_w_lm(q, total_momentum_d_vec, grid$gamma[i],         1, grid$l[i], grid$m[i]))
 4: FUN(X[[i]], ...)
 5: lapply(1:nrow(grid), function(i) {    print(q)    print(grid[i, ])    print(total_momentum_d_vec)    data.frame(spin_l = grid$l[i], spin_m = grid$m[i], boost_gamma = grid$gamma[i],         w = scattering_w_lm(q, total_momentum_d_vec, grid$gamma[i],             1, grid$l[i], grid$m[i]))})
 6: func(param_row, value_row)
 7: FUN(X[[i]], ...)
 8: lapply(X = S, FUN = FUN, ...)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
13: try(lapply(X = S, FUN = FUN, ...), silent = TRUE)
14: sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE))
15: FUN(X[[i]], ...)
16: lapply(seq_len(cores), inner.do)
17: parallel::mclapply(1:nrow(joined$param), closure)
18: pvcall(.func, rho_kinematics)
19: as.data.frame(pv$param)
20: make_summary(pvcall(.func, rho_kinematics))
An irrecoverable exception occurred. R is aborting now ...
```

And this also occurs with just one thread (using `lapply`):

```
# q:
 [1] 0.0000000 0.6666667 1.3333333 2.0000000 2.6666667 3.3333333 4.0000000
 [8] 4.6666667 5.3333333 6.0000000
# more parameters
  l  m gamma
1 2 -2     1
# total_momentum_d_vec
[1] 0 0 0

 *** caught segfault ***
address 0x5653abf6c000, cause 'memory not mapped'

Traceback:
 1: LuescherZeta(qsq = rel_momentum_q^2, l = spin_l, m = spin_m,     dvec = total_momentum_d_vec, gamma = boost_gamma, ...)
 2: scattering_w_lm(q, total_momentum_d_vec, grid$gamma[i], 1, grid$l[i],     grid$m[i])
 3: data.frame(spin_l = grid$l[i], spin_m = grid$m[i], boost_gamma = grid$gamma[i],     w = scattering_w_lm(q, total_momentum_d_vec, grid$gamma[i],         1, grid$l[i], grid$m[i]))
 4: FUN(X[[i]], ...)
 5: lapply(1:nrow(grid), function(i) {    print(q)    print(grid[i, ])    print(total_momentum_d_vec)    data.frame(spin_l = grid$l[i], spin_m = grid$m[i], boost_gamma = grid$gamma[i],         w = scattering_w_lm(q, total_momentum_d_vec, grid$gamma[i],             1, grid$l[i], grid$m[i]))})
 6: func(param_row, value_row)
 7: FUN(X[[i]], ...)
 8: lapply(1:nrow(joined$param), closure)
 9: pvcall(.func, rho_kinematics, serial = TRUE)
10: as.data.frame(pv$param)
11: make_summary(pvcall(.func, rho_kinematics, serial = TRUE))
An irrecoverable exception occurred. R is aborting now ...
```

Likely I call the function wrong as it at least does not crash for all the other inputs before. Perhaps we can add more pre-condition checks to the function to make it safer to use?

**Comment by martin-ueding** [comment]
Using `R --debugger gdb` I managed to obtain a backtrace:

```
Program received signal SIGSEGV, Segmentation fault.

#0  0x00007fffe4f80fb8 in firstPart (Tolerance=Tolerance@entry=9.9999999999999995e-07, l=l@entry=2, m=m@entry=-2, 
    dVec=dVec@entry=0x5555596cd088, gamma=gamma@entry=1, Lamda=Lamda@entry=1, qSqur=qSqur@entry=0, 
    verbose=verbose@entry=0, rstatus=rstatus@entry=0x7ffffffe9da4) at firstPart.c:82
#1  0x00007fffe4f81e3b in luscherZeta (res=0x7ffffffe9db0, qsq=0, l=2, m=-2, gamma=1, lambda=1, dvec=0x5555596cd088, 
    tol=9.9999999999999995e-07, verbose=0, rstatus=0x7ffffffe9da4) at luscherZeta.c:14
```

I'm going through the code right now, but it seems a bit opaque to me. From what I understand the memory region should always be valid because the allocated memory is always large enough and the `for`-loops do not exceed the bounds that were set in the allocation function. 

![screenshot_20180625_181235](https://user-images.githubusercontent.com/976924/41862622-bf3b28da-78a4-11e8-808b-f73b3c512c48.png)

I'll try to understand every line of this code next, along the way I will write some more comments.

**Comment by martin-ueding** [comment]
I have added three characters and changed one. The issue is not fixed, but it is now less likely to occur. It does not occur for me right now, so that's good enough then.
